# Pandas

### Pandas is an open-source software library for the Python programming language providing high-performance, easy-to-use data structures and analysis tools. It is a cornerstone of modern data science workflows, enabling efficient manipulation and analysis of structured data such as tables or time series.

### Handles data (tables like Excel)

In [19]:
# Create DataFrame and View data

import pandas as pd

data = {
    "rooms": [2, 1, 3, 5, 6, 7],
    "distance": [1.5, 5, 1, 3, 2, 4.5],
    "wifi": [1, 0, 1, 0, 1, 0],
    "rating": [4.5, 3.0, 4.8, 3.2, 4.1, 4.4]
}

df = pd.DataFrame(data)
print(df)

   rooms  distance  wifi  rating
0      2       1.5     1     4.5
1      1       5.0     0     3.0
2      3       1.0     1     4.8
3      5       3.0     0     3.2
4      6       2.0     1     4.1
5      7       4.5     0     4.4

In [20]:
# Shows the first 5 rows of your data

df.head()

   rooms  distance  wifi  rating
0      2       1.5     1     4.5
1      1       5.0     0     3.0
2      3       1.0     1     4.8
3      5       3.0     0     3.2
4      6       2.0     1     4.1

In [28]:
# Shows the given first n number of rows of your data

df.head(2)

   rooms  distance  wifi  rating
0      2       1.5     1     4.5
1      1       5.0     0     3.0

In [29]:
# Gives summary statistics of your data

df.describe()

          rooms  distance      wifi    rating
count  6.000000  6.000000  6.000000  6.000000
mean   4.000000  2.833333  0.500000  4.000000
std    2.366432  1.632993  0.547723  0.734847
min    1.000000  1.000000  0.000000  3.000000
25%    2.250000  1.625000  0.000000  3.425000
50%    4.000000  2.500000  0.500000  4.250000
75%    5.750000  4.125000  1.000000  4.475000
max    7.000000  5.000000  1.000000  4.800000

In [30]:
# Select column

df["rooms"]

0    2
1    1
2    3
3    5
4    6
5    7
Name: rooms, dtype: int64

In [31]:
# Filter data

df[df["rating"] > 4]

   rooms  distance  wifi  rating
0      2       1.5     1     4.5
2      3       1.0     1     4.8
4      6       2.0     1     4.1
5      7       4.5     0     4.4